### ISSUE TITLE
gsuite to gsuite?

### ISSUE THREAD

**Issue by scr44tch** [Spazzlo/folderclone#148]
dumb question incoming:

is this working for gsuites aswell, i mean can i copy from gsuite to gsuite (diffrent organisations)?
or is it only possible to copy to a teamdrive (shared drive).

if its possible how do i get the SHARED_DRIVE_ID?

**Comment by Spazzlo** [comment]
you must copy to a shared drive, but organisation shouldn't matter
you can't copy to non-shared-drives because then the file's storage quota is held by the sa, which is only 15gb over the whole lifetime
to get the shared drive id, open the shared drive in your browser and look at the url and find the string of random letters. that should be your drive id.
