### ISSUE TITLE
source folder "Source_Folder_ID" cannot be read or is invalid

### ISSUE THREAD

**Issue by andrewmcd7** [Spazzlo/folderclone#81]
I have everything installed and ready to go but when running the final step 

multifolderclone -s SOURCE_FOLDER_ID -d DESTINATION_FOLDER_ID 

I getting "source folder id cannot be read or is invalid"

... any help would be appreciated.

**Comment by greinyer** [comment]
Hello, I have done all the steps, but when I enter the last command, multifolderclone -s SOURCE_FOLDER_ID -d DESTINATION_FOLDER_ID I get the following message: "source folder id cannot be read or is invalid", the folder from which I want to copy is totally public since I made it public myself, as I make sure that the accounts can access the folder, thank you.
