### ISSUE TITLE
folderclone taking abnormally long to create Drive services

### ISSUE THREAD

**Issue by SalmonSammun** [Spazzlo/folderclone#96]
As the title says, just trying to start a clone using 10 service accounts causes the command prompt to hang for about 20 minutes. I recall it being able to load 100 much faster, and I'm just curious what could be causing the slowdown?

**Comment by xd003** [comment]
Yes been facing this issue since the start , i thought its just me

**Comment by xd003** [comment]
@Spazzlo can you please look into this , the "creating XX drive services" takes more time for me than the actual cloning itself ,its gets stuck there for a very long time before proceeding further. Wastes a lot of time

**Comment by evertonstz** [comment]
I get the same strange behaviour. I don't know what's actually the source for the problem, but when creating the service accounts, it hangs on `Adding XXX users`, I know the last step for the user creation is downloading the accounts json files, so I went and took a look at the "accounts" folder, the json files are all there. It seems folderclone is actually hanging on _after_ it creates the users. **So the current hacky way around this part is check if you have all the json files into the accounts folder (should be the same as the XXX user it's hanging on creation), if you do, kill folderclone with control+C **

Also as @xd003 I'm also facing the same problem with `creating XX drive service`, for now I didn't find a hacky way around it tho :/

**Comment by Mz49** [comment]
Understood. I'll see if I can find that the underlying issue is.

**Comment by evertonstz** [comment]
So, I solved this problem. That solution I said above actually didn't work at all, my problem is that the Shared Drive was set to not allow people from outside my uni's domain, since the sockpuppet accounts are from outside their domains, folder-clone would just freeze because it was not actually able to add the sockpuppet accounts in this Shared Drive, so it just kinda hanged there. Solution was to just change the Shared Drive settings to allow accounts from outside my domain.
